const plans=[['subscriptions','assets/figma/category-ott.png','OTT','Subscriptions'],['combos','assets/figma/category-combos.png','Combos','More value together'],['software','assets/figma/category-software.png','Software','Tools & licenses'],['music','assets/figma/category-music.png','Music','Listen without limits'],['adult','assets/figma/category-gaming.png','Gaming','Private premium plans']];
const products=(window.BF_PRODUCTS||[]);
window.BuyFinix={products};const money=n=>'৳'+Number(n).toLocaleString('en-BD'),title=s=>s[0].toUpperCase()+s.slice(1);
const readCart=()=>{try{return JSON.parse(localStorage.getItem('buyfinix-cart'))||[]}catch{return []}};let cart=readCart();const saveCart=()=>localStorage.setItem('buyfinix-cart',JSON.stringify(cart));
function productCard(p){return `<article class="product-card" data-name="${p.name.toLowerCase()}" data-group="${p.group}"><a class="product-art" href="product.html?id=${p.id}"><img class="figma-card-art" src="${p.image}" alt="${p.name}" width="173" height="301"></a><div class="product-info"><h4><a href="product.html?id=${p.id}">${p.name}</a></h4><div class="price"><b>${money(p.price)}</b><span>/mo</span><del>${money(p.old)}</del></div><div class="card-actions"><button data-cart="${p.id}" aria-label="Add ${p.name} to cart">🛒</button><a class="buy" href="product.html?id=${p.id}">Buy now</a></div></div></article>`}
function renderPlans(){const el=document.querySelector('#plan-strip');if(el)el.innerHTML=plans.map(([g,i,n,d])=>`<button class="plan" data-group="${g}"><span class="plan-icon"><img src="${i}" alt="" width="50" height="50"></span><b>${n}</b><small>${d}</small></button>`).join('')}
function renderCatalog(){const el=document.querySelector('#catalog');if(!el)return;el.innerHTML=['subscriptions','combos','software'].map(g=>`<section class="product-group" id="${g}"><div class="group-head"><h3>${g==='combos'?'Combo Packs':title(g)}</h3><a href="shop.html?category=${g}">View all &nbsp;→</a></div><div class="product-grid">${products.filter(p=>p.group===g).map(productCard).join('')}</div></section>`).join('')}
function renderCart(){const count=cart.reduce((n,x)=>n+x.qty,0);document.querySelectorAll('#cart-count,[data-cart-count]').forEach(el=>el.textContent=count);const items=document.querySelector('#cart-items');if(items)items.innerHTML=count?cart.map(item=>{const p=products.find(x=>x.id===item.id);return p?`<div class="cart-item"><span class="cart-thumb">${p.image?`<img src="${p.image}" alt="" width="52" height="52">`:p.icon}</span><span><b>${p.name}</b><small>${p.duration} · Qty ${item.qty}</small></span><b>${money(p.price*item.qty)}</b><button data-remove="${p.id}" aria-label="Remove ${p.name}">×</button></div>`:''}).join(''):'<div class="empty-state"><b>Your cart is empty</b><p>Add a plan and it will appear here.</p><a href="shop.html">Browse plans</a></div>';const total=cart.reduce((n,item)=>{const p=products.find(x=>x.id===item.id);return n+(p?p.price*item.qty:0)},0);const el=document.querySelector('#cart-total');if(el)el.textContent=count?money(total):'—'}
function openCart(){const drawer=document.querySelector('#cart-drawer');drawer?.classList.add('open');drawer?.setAttribute('aria-hidden','false');document.querySelector('#scrim')?.classList.add('open');document.body.classList.add('no-scroll');document.querySelector('#cart-close')?.focus()}
function closeLayers(){const drawer=document.querySelector('#cart-drawer');drawer?.classList.remove('open');drawer?.setAttribute('aria-hidden','true');document.querySelector('#mobile-menu')?.classList.remove('open');document.querySelector('#scrim')?.classList.remove('open');document.body.classList.remove('no-scroll')}
renderPlans();renderCatalog();renderCart();
document.addEventListener('click',e=>{const add=e.target.closest('[data-cart]');if(add){e.preventDefault();const id=Number(add.dataset.cart),item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});saveCart();renderCart();openCart();return}const remove=e.target.closest('[data-remove]');if(remove){cart=cart.filter(x=>x.id!==Number(remove.dataset.remove));saveCart();renderCart()}const plan=e.target.closest('.plan[data-group]');if(plan)location.href=`shop.html?category=${plan.dataset.group}`});
document.querySelector('#cart-open')?.addEventListener('click',openCart);document.querySelector('#cart-close')?.addEventListener('click',closeLayers);document.querySelector('#scrim')?.addEventListener('click',closeLayers);document.querySelector('#menu-open')?.addEventListener('click',()=>{document.querySelector('#mobile-menu')?.classList.add('open');document.querySelector('#scrim')?.classList.add('open')});document.querySelector('#menu-close')?.addEventListener('click',closeLayers);
const modal=document.querySelector('#search-modal'),input=document.querySelector('#search-input'),results=document.querySelector('#search-results');function renderSearch(q=''){if(!results)return;const term=q.trim().toLowerCase(),matches=term?products.filter(p=>p.name.toLowerCase().includes(term)||p.group.includes(term)):products.slice(0,5);results.innerHTML=matches.length?matches.slice(0,8).map(p=>`<a href="product.html?id=${p.id}"><span class="search-thumb">${p.image?`<img src="${p.image}" alt="" width="54" height="54">`:p.icon}</span><b>${p.name}<small>${title(p.group)} · ${p.duration}</small></b><strong>${money(p.price)}</strong></a>`).join(''):'<div class="empty-state"><b>No matching plans</b><p>Try Netflix, software, music or combo.</p></div>'}
document.querySelector('#search-open')?.addEventListener('click',()=>{modal?.classList.add('open');modal?.setAttribute('aria-hidden','false');setTimeout(()=>input?.focus(),50)});document.querySelector('#search-close')?.addEventListener('click',()=>{modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true')});input?.addEventListener('input',e=>renderSearch(e.target.value));renderSearch();document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal?.classList.remove('open');closeLayers()}});
document.querySelectorAll('.faq-list details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('.faq-list details').forEach(x=>{if(x!==d)x.open=false})}));let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});document.querySelector('#install-app')?.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice}else alert('Use your browser menu and choose Add to Home Screen.')});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js?v=nav6');
const rail=document.querySelector('.brand-rail');if(rail){rail.innerHTML+=rail.innerHTML;rail.classList.add('is-moving')}

document.querySelectorAll('.nav-drop>button').forEach(button=>{
  const drop=button.parentElement;
  button.addEventListener('click',event=>{
    event.stopPropagation();
    const open=!drop.classList.contains('open');
    document.querySelectorAll('.nav-drop.open').forEach(item=>{item.classList.remove('open');item.querySelector('button')?.setAttribute('aria-expanded','false')});
    drop.classList.toggle('open',open);
    button.setAttribute('aria-expanded',String(open));
  });
  button.addEventListener('keydown',event=>{
    if(event.key==='ArrowDown'){event.preventDefault();drop.classList.add('open');button.setAttribute('aria-expanded','true');drop.querySelector('a')?.focus()}
  });
});
document.addEventListener('click',()=>document.querySelectorAll('.nav-drop.open').forEach(item=>{item.classList.remove('open');item.querySelector('button')?.setAttribute('aria-expanded','false')}));

const storyTrack=document.querySelector('.story-track');if(storyTrack&&!storyTrack.dataset.cloned){const original=storyTrack.innerHTML;storyTrack.innerHTML=original+original+original;storyTrack.dataset.cloned='true'}
