document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="extras.css">');
const plans=[['subscriptions','▻','Subscriptions','OTT & premium access'],['combos','🎁','Combo Packs','More value together'],['software','▰','Software','Tools & licenses'],['music','♫','Music','Listen without limits'],['gaming','♜','Gaming','Keys & top-ups']];
const products=[
{id:1,group:'subscriptions',name:'Netflix Premium 4K',price:399,old:500,icon:'N',bg:'linear-gradient(#0d0d0d 0 58%,#07578b 58%)'},{id:2,group:'subscriptions',name:'Prime Video 4K',price:249,old:350,icon:'prime',bg:'#1681ee'},{id:3,group:'subscriptions',name:'Disney+ Premium',price:299,old:450,icon:'D+',bg:'linear-gradient(135deg,#0689ef,#111c87)'},{id:4,group:'subscriptions',name:'Spotify Premium',price:199,old:360,icon:'●',bg:'linear-gradient(135deg,#0b2519,#1eb85b)'},{id:5,group:'subscriptions',name:'YouTube Premium',price:199,old:300,icon:'▶',bg:'linear-gradient(135deg,#141414,#d91c29)'},{id:6,group:'subscriptions',name:'Apple TV+',price:249,old:399,icon:'tv+',bg:'linear-gradient(135deg,#555,#111)'},{id:7,group:'subscriptions',name:'Crunchyroll Premium',price:299,old:450,icon:'C',bg:'linear-gradient(135deg,#ff8b10,#e74409)'},{id:8,group:'subscriptions',name:'Premium VPN',price:899,old:1399,icon:'◈',bg:'linear-gradient(135deg,#0e736e,#162d57)'},{id:9,group:'subscriptions',name:'Hoichoi Premium',price:199,old:299,icon:'H',bg:'linear-gradient(135deg,#f21e30,#59172e)'},{id:10,group:'subscriptions',name:'Amazon Prime',price:299,old:450,icon:'a',bg:'linear-gradient(135deg,#15a1d5,#142a68)'},
{id:11,group:'combos',name:'Netflix + Prime Combo',price:599,old:850,icon:'2×',bg:'linear-gradient(135deg,#d91625,#1681ee)'},{id:12,group:'combos',name:'Entertainment 3-in-1',price:749,old:999,icon:'3×',bg:'linear-gradient(135deg,#713de0,#e52a84)'},{id:13,group:'combos',name:'Music Duo Pack',price:349,old:560,icon:'♫+',bg:'linear-gradient(135deg,#1cb85b,#fa315f)'},{id:14,group:'combos',name:'Creator Combo',price:1299,old:1999,icon:'✦',bg:'linear-gradient(135deg,#5d38db,#ec4d73)'},{id:15,group:'combos',name:'AI Power Pack',price:1999,old:2799,icon:'AI',bg:'linear-gradient(135deg,#10463d,#8b5eeb)'},
{id:16,group:'software',name:'Adobe Creative Cloud',price:949,old:1499,icon:'A',bg:'linear-gradient(135deg,#7027de,#dc3f85)'},{id:17,group:'software',name:'Windows 11 Pro Key',price:599,old:999,icon:'⊞',bg:'linear-gradient(135deg,#0871ce,#33b4ea)'},{id:18,group:'software',name:'Microsoft 365',price:799,old:1299,icon:'M',bg:'linear-gradient(135deg,#ee5225,#f3a51f)'},{id:19,group:'software',name:'Canva Pro',price:299,old:499,icon:'C',bg:'linear-gradient(135deg,#02c3cc,#7a55e6)'},{id:20,group:'software',name:'ChatGPT Plus',price:1499,old:1999,icon:'✺',bg:'linear-gradient(135deg,#10463d,#20a17c)'},{id:21,group:'software',name:'Google AI Pro',price:1699,old:2499,icon:'G',bg:'linear-gradient(135deg,#346fe5,#d93d87)'},{id:22,group:'software',name:'QuillBot Premium',price:499,old:799,icon:'Q',bg:'linear-gradient(135deg,#0ca87a,#075948)'},{id:23,group:'software',name:'CapCut Pro',price:399,old:699,icon:'X',bg:'linear-gradient(135deg,#111,#464646)'},{id:24,group:'software',name:'LinkedIn Premium',price:999,old:1599,icon:'in',bg:'linear-gradient(135deg,#0866a8,#24a1df)'},{id:25,group:'software',name:'Coursera Plus',price:1199,old:1999,icon:'C+',bg:'linear-gradient(135deg,#0759d8,#103d98)'}];
let cart=[];const money=n=>'৳'+n.toLocaleString('en-BD');const title=s=>s[0].toUpperCase()+s.slice(1);
function productCard(p){return `<article class="product-card" data-name="${p.name.toLowerCase()}"><a class="product-art" href="product.html?id=${p.id}" style="background:${p.bg}"><span class="instant-tag">⚡ INSTANT</span>${p.icon}</a><div class="product-info"><h4><a href="product.html?id=${p.id}">${p.name}</a></h4><div class="price"><b>${money(p.price)}</b><span>/mo</span><del>${money(p.old)}</del></div><div class="card-actions"><button data-cart="${p.id}" aria-label="Add ${p.name} to cart">🛒</button><button class="buy" data-cart="${p.id}">Buy now</button></div></div></article>`}
function renderPlans(){document.querySelector('#plan-strip').innerHTML=plans.map(([g,i,n,d])=>`<button class="plan" data-group="${g}"><span class="plan-icon">${i}</span><b>${n}</b><small>${d}</small></button>`).join('')}
function renderCatalog(){document.querySelector('#catalog').innerHTML=['subscriptions','combos','software'].map(g=>`<section class="product-group" id="${g}"><div class="group-head"><h3>${title(g)}</h3><button>View all &nbsp;→</button></div><div class="product-grid">${products.filter(p=>p.group===g).map(productCard).join('')}</div></section>`).join('')}
function renderCart(){document.querySelector('#cart-count').textContent=cart.length;document.querySelector('#cart-items').innerHTML=cart.length?cart.map(p=>`<div class="cart-item"><span><b>${p.name}</b><small>Instant delivery</small></span><b>${money(p.price)}</b></div>`).join(''):'<p>Your cart is empty.</p>';document.querySelector('#cart-total').textContent=cart.length?money(cart.reduce((n,p)=>n+p.price,0)):'—'}
function openCart(){document.querySelector('#cart-drawer').classList.add('open');document.querySelector('#scrim').classList.add('open')}function closeCart(){document.querySelector('#cart-drawer').classList.remove('open');document.querySelector('#scrim').classList.remove('open')}
document.querySelector('#plan-strip').addEventListener('click',e=>{const p=e.target.closest('[data-group]');if(p)location.href=`shop.html?category=${p.dataset.group}`});document.querySelector('#catalog').addEventListener('click',e=>{const id=Number(e.target.dataset.cart);if(id){cart.push(products.find(p=>p.id===id));renderCart();openCart()}});document.querySelector('#cart-open').onclick=openCart;document.querySelector('#cart-close').onclick=closeCart;document.querySelector('#scrim').onclick=closeCart;document.querySelector('#search-open').onclick=()=>{document.querySelector('#search-modal').classList.add('open');document.querySelector('#search-input').focus()};document.querySelector('#search-close').onclick=()=>document.querySelector('#search-modal').classList.remove('open');document.querySelector('#search-input').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.product-card').forEach(c=>c.style.display=c.dataset.name.includes(q)?'block':'none')};document.querySelector('#menu-open').onclick=()=>document.querySelector('#mobile-menu').classList.add('open');document.querySelector('#menu-close').onclick=()=>document.querySelector('#mobile-menu').classList.remove('open');let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});document.querySelector('#install-app').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice}else alert('Use your browser menu and choose Add to Home Screen.')};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderPlans();renderCatalog();renderCart();
