document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="extras.css">');
const plans=[['subscriptions','assets/figma/category-ott.png','OTT','Subscriptions'],['combos','assets/figma/category-combos.png','Combos','More value together'],['software','assets/figma/category-software.png','Software','Tools & licenses'],['music','assets/figma/category-music.png','Music','Listen without limits'],['adult','assets/figma/category-gaming.png','Gaming','Private premium plans']];
const products=[
{id:1,group:'subscriptions',name:'Netflix Premium 4K',price:399,old:500,icon:'N',bg:'linear-gradient(145deg,#101010,#c91622)',duration:'month'},
{id:2,group:'subscriptions',name:'Prime Video 4K',price:249,old:350,icon:'prime',bg:'linear-gradient(145deg,#159be8,#144c93)',duration:'month'},
{id:3,group:'subscriptions',name:'Disney+ Premium',price:299,old:450,icon:'D+',bg:'linear-gradient(145deg,#118be8,#141b72)',duration:'month'},
{id:4,group:'subscriptions',name:'YouTube Premium',price:199,old:300,icon:'▶',bg:'linear-gradient(145deg,#171717,#ce1725)',duration:'month'},
{id:5,group:'subscriptions',name:'Apple TV+',price:249,old:399,icon:'tv+',bg:'linear-gradient(145deg,#666,#121212)',duration:'month'},
{id:6,group:'subscriptions',name:'Premium VPN',price:899,old:1399,icon:'◈',bg:'linear-gradient(145deg,#137e76,#142b54)',duration:'year'},
{id:7,group:'combos',name:'Netflix + Prime Combo',price:599,old:850,icon:'2×',bg:'linear-gradient(145deg,#d91625,#1681ee)',duration:'month'},
{id:8,group:'combos',name:'Entertainment 3-in-1',price:749,old:999,icon:'3×',bg:'linear-gradient(145deg,#713de0,#e52a84)',duration:'month'},
{id:9,group:'combos',name:'Music Duo Pack',price:349,old:560,icon:'♫+',bg:'linear-gradient(145deg,#1cb85b,#fa315f)',duration:'month'},
{id:10,group:'combos',name:'Creator Combo',price:1299,old:1999,icon:'✦',bg:'linear-gradient(145deg,#5d38db,#ec4d73)',duration:'month'},
{id:11,group:'software',name:'Adobe Creative Cloud',price:949,old:1499,icon:'A',bg:'linear-gradient(145deg,#7027de,#dc3f85)',duration:'month'},
{id:12,group:'software',name:'Windows 11 Pro Key',price:599,old:999,icon:'⊞',bg:'linear-gradient(145deg,#0871ce,#33b4ea)',duration:'lifetime'},
{id:13,group:'software',name:'Microsoft 365',price:799,old:1299,icon:'M',bg:'linear-gradient(145deg,#ee5225,#f3a51f)',duration:'year'},
{id:14,group:'software',name:'Canva Pro',price:299,old:499,icon:'C',bg:'linear-gradient(145deg,#02c3cc,#7a55e6)',duration:'month'},
{id:15,group:'software',name:'ChatGPT Plus',price:1499,old:1999,icon:'✺',bg:'linear-gradient(145deg,#10463d,#20a17c)',duration:'month'},
{id:16,group:'music',name:'Spotify Premium',price:199,old:360,icon:'●',bg:'linear-gradient(145deg,#0b2519,#1eb85b)',duration:'month'}];
window.BuyFinix={products};const money=n=>'৳'+Number(n).toLocaleString('en-BD'),title=s=>s[0].toUpperCase()+s.slice(1);
const readCart=()=>{try{return JSON.parse(localStorage.getItem('buyfinix-cart'))||[]}catch{return []}};let cart=readCart();const saveCart=()=>localStorage.setItem('buyfinix-cart',JSON.stringify(cart));
function productCard(p){return `<article class="product-card" data-name="${p.name.toLowerCase()}" data-group="${p.group}"><a class="product-art" href="product.html?id=${p.id}" style="background:${p.bg}"><span class="instant-tag">⚡ INSTANT</span><span class="product-mark">${p.icon}</span></a><div class="product-info"><h4><a href="product.html?id=${p.id}">${p.name}</a></h4><div class="price"><b>${money(p.price)}</b><span>/${p.duration}</span><del>${money(p.old)}</del></div><div class="card-actions"><button data-cart="${p.id}" aria-label="Add ${p.name} to cart">＋</button><a class="buy" href="product.html?id=${p.id}">Buy now</a></div></div></article>`}
function renderPlans(){const el=document.querySelector('#plan-strip');if(el)el.innerHTML=plans.map(([g,i,n,d])=>`<button class="plan" data-group="${g}"><span class="plan-icon"><img src="${i}" alt="" width="50" height="50"></span><b>${n}</b><small>${d}</small></button>`).join('')}
function renderCatalog(){const el=document.querySelector('#catalog');if(!el)return;el.innerHTML=['subscriptions','combos','software'].map(g=>`<section class="product-group" id="${g}"><div class="group-head"><h3>${g==='combos'?'Combo Packs':title(g)}</h3><a href="shop.html?category=${g}">View all &nbsp;→</a></div><div class="product-grid">${products.filter(p=>p.group===g).slice(0,5).map(productCard).join('')}</div></section>`).join('')}
function renderCart(){const count=cart.reduce((n,x)=>n+x.qty,0);document.querySelectorAll('#cart-count,[data-cart-count]').forEach(el=>el.textContent=count);const items=document.querySelector('#cart-items');if(items)items.innerHTML=count?cart.map(item=>{const p=products.find(x=>x.id===item.id);return p?`<div class="cart-item"><span class="cart-thumb" style="background:${p.bg}">${p.icon}</span><span><b>${p.name}</b><small>${p.duration} · Qty ${item.qty}</small></span><b>${money(p.price*item.qty)}</b><button data-remove="${p.id}" aria-label="Remove ${p.name}">×</button></div>`:''}).join(''):'<div class="empty-state"><b>Your cart is empty</b><p>Add a plan and it will appear here.</p><a href="shop.html">Browse plans</a></div>';const total=cart.reduce((n,item)=>{const p=products.find(x=>x.id===item.id);return n+(p?p.price*item.qty:0)},0);const el=document.querySelector('#cart-total');if(el)el.textContent=count?money(total):'—'}
function openCart(){document.querySelector('#cart-drawer')?.classList.add('open');document.querySelector('#scrim')?.classList.add('open');document.body.classList.add('no-scroll')}
function closeLayers(){document.querySelector('#cart-drawer')?.classList.remove('open');document.querySelector('#mobile-menu')?.classList.remove('open');document.querySelector('#scrim')?.classList.remove('open');document.body.classList.remove('no-scroll')}
renderPlans();renderCatalog();renderCart();
document.addEventListener('click',e=>{const add=e.target.closest('[data-cart]');if(add){e.preventDefault();const id=Number(add.dataset.cart),item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});saveCart();renderCart();openCart();return}const remove=e.target.closest('[data-remove]');if(remove){cart=cart.filter(x=>x.id!==Number(remove.dataset.remove));saveCart();renderCart()}const plan=e.target.closest('.plan[data-group]');if(plan)location.href=`shop.html?category=${plan.dataset.group}`});
document.querySelector('#cart-open')?.addEventListener('click',openCart);document.querySelector('#cart-close')?.addEventListener('click',closeLayers);document.querySelector('#scrim')?.addEventListener('click',closeLayers);document.querySelector('#menu-open')?.addEventListener('click',()=>{document.querySelector('#mobile-menu')?.classList.add('open');document.querySelector('#scrim')?.classList.add('open')});document.querySelector('#menu-close')?.addEventListener('click',closeLayers);
const modal=document.querySelector('#search-modal'),input=document.querySelector('#search-input'),results=document.querySelector('#search-results');function renderSearch(q=''){if(!results)return;const term=q.trim().toLowerCase(),matches=term?products.filter(p=>p.name.toLowerCase().includes(term)||p.group.includes(term)):products.slice(0,5);results.innerHTML=matches.length?matches.slice(0,8).map(p=>`<a href="product.html?id=${p.id}"><span style="background:${p.bg}">${p.icon}</span><b>${p.name}<small>${title(p.group)} · ${p.duration}</small></b><strong>${money(p.price)}</strong></a>`).join(''):'<div class="empty-state"><b>No matching plans</b><p>Try Netflix, software, music or combo.</p></div>'}
document.querySelector('#search-open')?.addEventListener('click',()=>{modal?.classList.add('open');modal?.setAttribute('aria-hidden','false');setTimeout(()=>input?.focus(),50)});document.querySelector('#search-close')?.addEventListener('click',()=>{modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true')});input?.addEventListener('input',e=>renderSearch(e.target.value));renderSearch();document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal?.classList.remove('open');closeLayers()}});
document.querySelectorAll('.faq-list details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('.faq-list details').forEach(x=>{if(x!==d)x.open=false})}));let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});document.querySelector('#install-app')?.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice}else alert('Use your browser menu and choose Add to Home Screen.')});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js');
const rail=document.querySelector('.brand-rail');if(rail){rail.innerHTML+=rail.innerHTML;rail.classList.add('is-moving')}
