const demoProducts=[
{id:1,name:'Netflix Premium 4K',group:'subscriptions',price:399,old:500,icon:'N'},
{id:2,name:'Prime Video 4K',group:'subscriptions',price:249,old:350,icon:'prime'},
{id:3,name:'Disney+ Premium',group:'subscriptions',price:299,old:450,icon:'D+'},
{id:4,name:'Spotify Premium',group:'music',price:199,old:360,icon:'●'},
{id:5,name:'ChatGPT Plus',group:'software',price:1499,old:1999,icon:'✺'},
{id:6,name:'Adobe Creative Cloud',group:'software',price:949,old:1499,icon:'A'},
{id:7,name:'Canva Pro',group:'software',price:299,old:499,icon:'C'},
{id:8,name:'Netflix + Prime Combo',group:'combos',price:599,old:850,icon:'2×'},
{id:9,name:'Entertainment 3-in-1',group:'combos',price:749,old:999,icon:'3×'},
{id:10,name:'Windows 11 Pro Key',group:'software',price:599,old:999,icon:'⊞'},
{id:11,name:'Microsoft 365',group:'software',price:799,old:1299,icon:'M'},
{id:12,name:'Premium VPN',group:'subscriptions',price:899,old:1399,icon:'◈'}];
const money=n=>'৳'+n.toLocaleString('en-BD'),colors={subscriptions:'#164e8d',music:'#15964b',software:'#6736a6',combos:'#cc325f',adult:'#252525',more:'#6a782c'};
const card=p=>`<article class="product-card"><a class="product-art" href="product.html?id=${p.id}" style="background:linear-gradient(145deg,${colors[p.group]||'#172217'},#172217)"><span class="instant-tag">⚡ INSTANT</span><span class="product-mark">${p.icon}</span></a><div class="product-info"><h4><a href="product.html?id=${p.id}">${p.name}</a></h4><div class="price"><b>${money(p.price)}</b><span>/mo</span><del>${money(p.old)}</del></div><div class="card-actions"><button aria-label="Add ${p.name}">＋</button><a class="buy" href="product.html?id=${p.id}">Buy now</a></div></div></article>`;
const grid=document.querySelector('#shop-grid'),search=document.querySelector('#shop-search'),category=document.querySelector('#shop-category'),sort=document.querySelector('#shop-sort'),count=document.querySelector('#product-count'),tabs=document.querySelector('#category-tabs');
function shopState(){const params=new URLSearchParams(location.search);return{q:params.get('q')||'',category:params.get('category')||'all',sort:params.get('sort')||'featured'}}
function renderShop(updateUrl=false){if(!grid)return;const state={q:search?.value.trim()||'',category:category?.value||'all',sort:sort?.value||'featured'};let list=demoProducts.filter(p=>(state.category==='all'||p.group===state.category)&&p.name.toLowerCase().includes(state.q.toLowerCase()));if(state.sort==='Price low to high')list.sort((a,b)=>a.price-b.price);if(state.sort==='Newest')list.reverse();grid.innerHTML=list.length?list.map(card).join(''):'<div class="empty-state"><b>No matching plans</b><p>Clear a filter or try another search.</p></div>';if(count)count.textContent=`${list.length} plan${list.length===1?'':'s'} available`;tabs?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.category===state.category));if(updateUrl){const params=new URLSearchParams();if(state.q)params.set('q',state.q);if(state.category!=='all')params.set('category',state.category);if(state.sort!=='featured')params.set('sort',state.sort);history.replaceState(null,'',`${location.pathname}${params.toString()?'?'+params:''}`)}}
if(grid){const state=shopState();search.value=state.q;category.value=state.category;renderShop();search.addEventListener('input',()=>renderShop(true));category.addEventListener('change',()=>renderShop(true));sort.addEventListener('change',()=>renderShop(true));tabs.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;category.value=b.dataset.category;renderShop(true)})}
document.querySelectorAll('[data-duration]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-duration]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#detail-price').textContent=b.dataset.price}));
document.querySelectorAll('form.demo-form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();f.querySelector('.form-status').textContent='Thanks — your request has been received.'}));
const otp=document.querySelector('#otp-form'),verify=document.querySelector('#verify-form');otp?.addEventListener('submit',e=>{e.preventDefault();const email=document.querySelector('#otp-email').value;otp.querySelector('.form-status').textContent=`A code was requested for ${email}. Connect the email provider to deliver production OTPs.`;verify.hidden=false;document.querySelector('#otp-code').focus()});verify?.addEventListener('submit',e=>{e.preventDefault();verify.querySelector('.form-status').textContent='Email verified for this preview session.'});
